package jogo.logica;

public enum Propriedade {
    ATUALIZAR_ESTADO,
    ATUALIZAR_TABULEIRO,
    ATUALIZAR_LISTA_JOGADORES,
    ATUALIZAR_JOGADOR_ATUAL,
    ATUALIZAR_PERGUNTA_MINIJOGO,
    ATUALIZAR_VENCEDOR,
    FIM_MINIJOGO,
    COMECAR_REPLAY
}
