CC = gcc
SOURCE = $(wildcard *.c)
EXECUTABLE = diversidade

all: 
	@ $(CC) $(SOURCE) -o $(EXECUTABLE)
	@ echo "Compilation finished sucessfully."

clean:
	@ rm $(EXECUTABLE).exe -f
	@ echo "Directory cleaned."